# Generated by Django 5.1.15 on 2026-06-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Church', max_length=200)),
                ('timezone', models.CharField(default='America/New_York', max_length=63)),
                ('reminder_days_before', models.CharField(default='7,1', help_text='Comma-separated days before shift to send reminders', max_length=50)),
                ('default_serving_frequency_weeks', models.PositiveSmallIntegerField(default=4, help_text='Target weeks between assignments for a volunteer')),
            ],
            options={
                'verbose_name_plural': 'church settings',
            },
        ),
    ]
