# Generated by Django 5.2.15 on 2026-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_church_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchBranding',
            fields=[
            ],
            options={
                'verbose_name': 'church branding',
                'verbose_name_plural': 'church branding',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.churchsettings',),
        ),
        migrations.CreateModel(
            name='ChurchLogo',
            fields=[
            ],
            options={
                'verbose_name': 'church logo',
                'verbose_name_plural': 'church logos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.churchsettings',),
        ),
        migrations.AlterField(
            model_name='churchsettings',
            name='branding_css',
            field=models.TextField(blank=True, default='@import url("https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Open+Sans:wght@400;500;600&display=swap");\n\n:root {\n  --mm-brand: #332f2e;\n  --mm-brand-dark: #262322;\n  --mm-brand-muted: #5c5654;\n  --mm-brand-accent: #c9b8a8;\n  --mm-brand-bg: #faf8f6;\n  --mm-brand-surface: #ffffff;\n}\n\nbody {\n  font-family: "Open Sans", Arial, sans-serif;\n  background-color: var(--mm-brand-bg) !important;\n}\n\n.mm-brand-heading {\n  font-family: "Cormorant Garamond", Georgia, serif;\n}\n\n.mm-sidebar {\n  background-color: var(--mm-brand) !important;\n  border-color: var(--mm-brand-dark) !important;\n}\n\n.mm-sidebar-brand {\n  overflow: hidden;\n}\n\n.mm-sidebar .mm-brand-heading,\n.mm-sidebar .mm-brand-text {\n  color: #ffffff !important;\n}\n\n.mm-sidebar nav a {\n  color: rgba(255, 255, 255, 0.9);\n}\n\n.mm-sidebar nav a:hover {\n  background-color: rgba(255, 255, 255, 0.1) !important;\n  color: #ffffff;\n}\n\n.mm-sidebar hr,\n.mm-sidebar .border-slate-200 {\n  border-color: rgba(255, 255, 255, 0.15) !important;\n}\n\n.mm-sidebar .text-slate-400,\n.mm-sidebar .text-slate-700 {\n  color: rgba(255, 255, 255, 0.65) !important;\n}\n\n.mm-sidebar .mm-brand-link {\n  color: var(--mm-brand-accent) !important;\n}\n\n.mm-sidebar .mm-brand-link:hover {\n  color: #ffffff !important;\n}\n\n.mm-mobile-header {\n  background-color: var(--mm-brand-surface) !important;\n  border-color: #e8e4e0 !important;\n}\n\n.mm-mobile-header .mm-brand-text,\n.mm-mobile-header .mm-brand-link {\n  color: var(--mm-brand) !important;\n}\n\n.btn-primary {\n  background-color: var(--mm-brand) !important;\n}\n\n.btn-primary:hover {\n  background-color: var(--mm-brand-dark) !important;\n}\n\n.text-indigo-600,\n.text-indigo-700,\n.text-indigo-800 {\n  color: var(--mm-brand) !important;\n}\n\n.hover\\:text-indigo-800:hover {\n  color: var(--mm-brand-dark) !important;\n}\n\n.border-indigo-200 {\n  border-color: #e8e0d8 !important;\n}\n\n.bg-indigo-50 {\n  background-color: #f5f0eb !important;\n}\n\n.input:focus,\n.checkbox-row input[type="checkbox"]:focus,\n.checkbox-list input[type="checkbox"]:focus {\n  border-color: var(--mm-brand-muted) !important;\n  --tw-ring-color: var(--mm-brand-muted) !important;\n}\n\n.checkbox-row input[type="checkbox"],\n.checkbox-list input[type="checkbox"] {\n  color: var(--mm-brand) !important;\n}\n', help_text='Custom CSS for app branding (colors, fonts, sidebar, buttons).'),
        ),
    ]
