# Generated by Django 5.1.15 on 2026-06-07 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('campuses', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('unfilled', 'Unfilled'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='scheduled', max_length=20)),
                ('slot_index', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campuses.serviceoccurrence')),
                ('team_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teams.teamrole')),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='accounts.volunteerprofile')),
            ],
            options={
                'ordering': ['service_occurrence', 'team_role', 'slot_index'],
                'constraints': [models.UniqueConstraint(fields=('service_occurrence', 'team_role', 'slot_index'), name='unique_role_slot_per_occurrence'), models.UniqueConstraint(condition=models.Q(('volunteer__isnull', False)), fields=('service_occurrence', 'volunteer'), name='unique_volunteer_per_occurrence')],
            },
        ),
        migrations.CreateModel(
            name='BlockOutDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_out_dates', to='accounts.volunteerprofile')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='scheduling__date_f5a2bf_idx')],
                'unique_together': {('volunteer', 'date')},
            },
        ),
    ]
